spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL # test ??? ??? ??? ??? ???? ???.
    username: sa # username? password? ??? ??? ??
    password:
    driver-class-name: org.h2.Driver


  jpa:
    properties:
      hibernate:
        format_sql: true # ???? query? ???

    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug